variables:
  conan.user: 'ccdc'
  conan.channel: 'testing'
  conan.package: 'zlib'
  conan.package_version: '1.2.11'
  conan.build_types:
    - Release
    - Debug
    - RelWithDebInfo
  # We use what is provided by the UsePythonVersion step in general
  conan.python: 'python'

resources:
  repositories:
    - repository: templates
      type: git
      name: ccdc-3rd-party/conan-azure-devops
      ref: refs/tags/development

  jobs:
  - job: Centos7
    pool:
      vmImage: "ubuntu-latest"
    # We use a container to run the build as we must be compatible with centos7's older glibc
    container: rockdreamer/centos7-gcc9:latest
    variables:
      conan.profile: centos7-gcc9-x86_64
      # We can't use UsePythonVersion on this VM so we have to be explicit
      conan.python: 'python3'
    steps:
      # No need to setup specific python, the container's python3 will be used
      - template: single-build.yml@templates

  - job: Ubuntu20-Gcc10
    pool:
      vmImage: "ubuntu-latest"
    # We use a container to run the build as we must be compatible with centos7's older glibc
    container: conanio/gcc10:latest
    variables:
      conan.profile: ubuntu20-gcc10-x86_64
      # We can't use UsePythonVersion on this VM so we have to be explicit
      conan.python: 'python3'
    steps:
      # No need to setup specific python, the container's python3 will be used
      - template: single-build.yml@templates

  - job: macOS
    pool:
      vmImage: "macOS-latest"
    variables:
      conan.profile: macos-xcode11-x86_64
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"
        displayName: "Use latest python 3.8"
      - template: single-build.yml@templates

  - job: WindowsVS2017
    pool:
      vmImage: "vs2017-win2016"
    variables:
      conan.profile: windows-msvc15-amd64
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"
        displayName: "Use latest python 3.8"
      - template: single-build.yml@templates

  - job: WindowsVS2019
    pool:
      vmImage: "windows-2019"
    variables:
      conan.profile: windows-msvc16-amd64
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"
        displayName: "Use latest python 3.8"
      - template: single-build.yml@templates
