variables:
  conan.user: 'ccdc'
  conan.channel: 'testing'
  conan.package: 'zlib'
  conan.package_version: '1.2.11'
  conan.python: 'python3'

jobs:
  - job: Centos7
    variables:
      conan.profile: centos7-gcc9-x86_64
    pool:
      vmImage: "ubuntu-latest"
    # We use a container to run the build as we must be compatible with centos7's older glibc
    container: rockdreamer/centos7-gcc9:latest
    steps:
      # No need to setup specific python, the container's python3 will be used
      - template: single-build.yml

  - job: macOS
    pool:
      vmImage: "macOS-latest"
    variables:
      conan.profile: macos-xcode11-x86_64
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"
        displayName: "Use latest python 3.8"
      - template: single-build.yml

  - job: WindowsVS2017
    pool:
      vmImage: "windows-2019"
    variables:
      conan.profile: windows-msvc15-amd64
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"
        displayName: "Use latest python 3.8"
      - template: single-build.yml

  - job: WindowsVS2019
    pool:
      vmImage: "windows-2019"
    variables:
      conan.profile: windows-msvc16-amd64
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"
        displayName: "Use latest python 3.8"
      - template: single-build.yml
